# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-13 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(default='2018-10-13'),
        ),
    ]
