# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20181016_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftDeletedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_task_id', models.IntegerField(default=0)),
                ('soft_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(default=b'2018-10-17'),
        ),
    ]
